### ISSUE TITLE
[Feature] Single Table Tournaments

### ISSUE THREAD

**Issue by elliottneilclark** [elliottneilclark/rs-poker#110]
One of the more common questions in poker is who would win if given stacks at a table and told to play until one remains. We should have that ability for `Agent`s.

The general idea is this:

Given: A way to create agents to compete and a starting state. Create a new simulation. Run it to completion. Then, start a new simulation using the output of the last. You will also need to progress the location of the dealer. 

## TODO

- [x] Formalize some Agent constructor trait that can be used to re-create agents.
- [x] Create code that will run multiple simulations back to back, using the stack sizes from the last simulation. Run until only one is left.
- [x] Add example code
- [ ] Add documentations
